/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FeaturesIndexRouteImport } from './routes/features.index'
import { Route as FeaturesLeadDatabasesRouteImport } from './routes/features.lead-databases'
import { Route as FeaturesEmailVerificationRouteImport } from './routes/features.email-verification'
import { Route as FeaturesDeliverabilityRouteImport } from './routes/features.deliverability'
import { Route as FeaturesColdEmailToolsRouteImport } from './routes/features.cold-email-tools'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FeaturesIndexRoute = FeaturesIndexRouteImport.update({
  id: '/features/',
  path: '/features/',
  getParentRoute: () => rootRouteImport,
} as any)
const FeaturesLeadDatabasesRoute = FeaturesLeadDatabasesRouteImport.update({
  id: '/features/lead-databases',
  path: '/features/lead-databases',
  getParentRoute: () => rootRouteImport,
} as any)
const FeaturesEmailVerificationRoute =
  FeaturesEmailVerificationRouteImport.update({
    id: '/features/email-verification',
    path: '/features/email-verification',
    getParentRoute: () => rootRouteImport,
  } as any)
const FeaturesDeliverabilityRoute = FeaturesDeliverabilityRouteImport.update({
  id: '/features/deliverability',
  path: '/features/deliverability',
  getParentRoute: () => rootRouteImport,
} as any)
const FeaturesColdEmailToolsRoute = FeaturesColdEmailToolsRouteImport.update({
  id: '/features/cold-email-tools',
  path: '/features/cold-email-tools',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/features/cold-email-tools': typeof FeaturesColdEmailToolsRoute
  '/features/deliverability': typeof FeaturesDeliverabilityRoute
  '/features/email-verification': typeof FeaturesEmailVerificationRoute
  '/features/lead-databases': typeof FeaturesLeadDatabasesRoute
  '/features/': typeof FeaturesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/features/cold-email-tools': typeof FeaturesColdEmailToolsRoute
  '/features/deliverability': typeof FeaturesDeliverabilityRoute
  '/features/email-verification': typeof FeaturesEmailVerificationRoute
  '/features/lead-databases': typeof FeaturesLeadDatabasesRoute
  '/features': typeof FeaturesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/features/cold-email-tools': typeof FeaturesColdEmailToolsRoute
  '/features/deliverability': typeof FeaturesDeliverabilityRoute
  '/features/email-verification': typeof FeaturesEmailVerificationRoute
  '/features/lead-databases': typeof FeaturesLeadDatabasesRoute
  '/features/': typeof FeaturesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/features/cold-email-tools'
    | '/features/deliverability'
    | '/features/email-verification'
    | '/features/lead-databases'
    | '/features/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/features/cold-email-tools'
    | '/features/deliverability'
    | '/features/email-verification'
    | '/features/lead-databases'
    | '/features'
  id:
    | '__root__'
    | '/'
    | '/features/cold-email-tools'
    | '/features/deliverability'
    | '/features/email-verification'
    | '/features/lead-databases'
    | '/features/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FeaturesColdEmailToolsRoute: typeof FeaturesColdEmailToolsRoute
  FeaturesDeliverabilityRoute: typeof FeaturesDeliverabilityRoute
  FeaturesEmailVerificationRoute: typeof FeaturesEmailVerificationRoute
  FeaturesLeadDatabasesRoute: typeof FeaturesLeadDatabasesRoute
  FeaturesIndexRoute: typeof FeaturesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/features/': {
      id: '/features/'
      path: '/features'
      fullPath: '/features/'
      preLoaderRoute: typeof FeaturesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/features/lead-databases': {
      id: '/features/lead-databases'
      path: '/features/lead-databases'
      fullPath: '/features/lead-databases'
      preLoaderRoute: typeof FeaturesLeadDatabasesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/features/email-verification': {
      id: '/features/email-verification'
      path: '/features/email-verification'
      fullPath: '/features/email-verification'
      preLoaderRoute: typeof FeaturesEmailVerificationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/features/deliverability': {
      id: '/features/deliverability'
      path: '/features/deliverability'
      fullPath: '/features/deliverability'
      preLoaderRoute: typeof FeaturesDeliverabilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/features/cold-email-tools': {
      id: '/features/cold-email-tools'
      path: '/features/cold-email-tools'
      fullPath: '/features/cold-email-tools'
      preLoaderRoute: typeof FeaturesColdEmailToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FeaturesColdEmailToolsRoute: FeaturesColdEmailToolsRoute,
  FeaturesDeliverabilityRoute: FeaturesDeliverabilityRoute,
  FeaturesEmailVerificationRoute: FeaturesEmailVerificationRoute,
  FeaturesLeadDatabasesRoute: FeaturesLeadDatabasesRoute,
  FeaturesIndexRoute: FeaturesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
